routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//  prefix tgat show at url is (adminPnel)
//  prefix tgat show at url is (adminPnel)


//  for language (  package laravel macamara )
Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function()
{
	Route::namespace('Front')->name('front.')->group(function()
	{

		Route::get('/','HomeController@index')->name('get.home.index')->middleware('getRoute');
		Route::get('/home/help','HomeController@help')->name('get.home.help')->middleware('getRoute');
		Route::get('/about','HomeController@about')->name('get.home.about')->middleware('getRoute');
		Route::post('/getInfo','HomeController@geoip')->name('post.home.geoip')->middleware('postRoute');

		

		// contact us page
		Route::get('/contact-us','ContactUsController@contact')->name('get.contactus.contact')->middleware('getRoute');
		Route::get('/help','ContactUsController@help')->name('get.contactus.help')->middleware('getRoute');
		// send message from contact us page 
		Route::post('/send-message','ContactUsController@sendMessage')->name('post.contactus.sendMessage')->middleware('postRoute');
		// gallery page
		// Route::get('/gallery','ContactUsController@gallery')->name('get.contactus.gallery')->middleware('getRoute');

		// portfolio page
		// Route::get('/portfolio','PortfolioController@portfolio')->name('get.portfolio.index')->middleware('getRoute');


		// services 
		Route::get('/services','ServiceController@all')->name('get.service.all')->middleware('getRoute');
		// show services according to category
		Route::get('/service/{slugCat}','ServiceController@category')->name('get.service.category')->middleware('getRoute');
		// show one service
		Route::get('/services/{slugService}','ServiceController@show')->name('get.service.show')->middleware('getRoute');
		// order this service
		// Route::post('/order','ServiceController@order')->name('post.service.order');




		// products  search
		Route::get('/products/search','ProductController@search')->name('get.product.search')->middleware('getRoute');
		// show products according to category
		Route::get('/product/{slugCat}','ProductController@category')->name('get.product.category')->middleware('getRoute');
		// show products according to sub category
		Route::get('/product/{slugCat}/{slugSubCat}','ProductController@subCategory')->name('get.product.subCategory')->middleware('getRoute');
		// show one product
		Route::get('/product/{slugCat}/{slugSubCat}/{slugProduct}','ProductController@show')->name('get.product.show')->middleware('getRoute');
		Route::post('/filter','ProductController@filter')->name('post.product.filter')->middleware('postRoute');

		

		// add this product to cart
		Route::post('/order','OrderController@order')->name('post.product.order')->middleware('postRoute');



		Route::get('/cart/show','CartController@show')->name('get.cart.show')->middleware('getRoute');
		Route::post('/cart/add','CartController@add')->name('post.cart.add')->middleware('postRoute');
		
		Route::get('/cart/edit','CartController@edit')->name('get.cart.edit')->middleware('getRoute');
		Route::post('/cart/update','CartController@update')->name('post.cart.update')->middleware('postRoute');
		Route::post('/cart/remove','CartController@remove')->name('post.cart.remove')->middleware('postRoute');
		Route::get('/cart/clear','CartController@clear')->name('get.cart.clear')->middleware('getRoute');
		Route::get('/cart/delete/{id}','CartController@delete')->name('get.cart.delete')->middleware('getRoute');


		Route::get('/order/checkout','OrderController@checkout')->name('get.order.checkout')->middleware('getRoute');
		Route::post('/order/sendOrder','OrderController@sendOrder')->name('post.order.sendOrder')->middleware('postRoute');

		// mobile
		Route::post('/cart/mobile/add','CartController@mobileAdd')->name('post.cart.mobileAdd')->middleware('postRoute');
		// filter
		Route::get('/sort','ProductController@sortProduct')->name('post.product.sortProduct')->middleware('getRoute');






		







		// Blog 
		Route::get('/blog','BlogController@index')->name('get.blog.index')->middleware('getRoute');
		Route::get('/blog/{slugBlog}','BlogController@show')->name('get.blog.show')->middleware('getRoute');

		// subscribe
		Route::post('/subscribe','ContactUsController@subscribe')->name('post.contactus.subscribe')->middleware('postRoute');



	

		Route::get('/page/{slugPage}','StaticPageController@show')->name('get.static.page')->middleware('getRoute');


			
	


		// customer area 

		Route::namespace('Client')->name('client.')->prefix('customer')->group(function()
		{
			if(!clientAuth()->user())
			{
				Route::get('/login','AuthController@login')->name('get.auth.login')->middleware('getRoute');
				Route::post('/login','AuthController@doLogin')->name('post.auth.doLogin')->middleware('postRoute');
				Route::get('/register','AuthController@register')->name('get.auth.register')->middleware('getRoute');
				Route::post('/register','AuthController@doRegister')->name('post.auth.doRegister')->middleware('postRoute');


				// reset password 

				Route::get('/forgot','ForgotController@forgot')->name('get.auth.forgot')->middleware('getRoute');
				Route::post('/forgot','ForgotController@forgotPassword')->name('post.auth.forgotPassword')->middleware('postRoute');


				Route::get('/change/password/{token}','ForgotController@changePassword')->middleware('getRoute');

				Route::post('/new/password','ForgotController@newPassword')->name('post.auth.newPassword')->middleware('postRoute');
				

			}
			


			
			//  admin is auth  ( function clientAuth() => this function return object of client if he is authunicated ) 
			Route::group(['middleware'=>'client:client'],function()
			{
				Route::get('/logout','AuthController@logout')->name('get.auth.logout')->middleware('getRoute');
				Route::get('/profile/{data}','ProfileController@index')->name('get.profile.index')->middleware('getRoute');
				Route::post('/profile','ProfileController@editProfile')->name('post.auth.editProfile')->middleware('postRoute');
				Route::post('/profile/password','ProfileController@editPassword')->name('post.auth.editPassword')->middleware('postRoute');



				Route::get('/order/{id}','ProfileController@showDatails')->name('get.order.showDatails')->middleware('getRoute');

				Route::get('/order/content/{id}','ProfileController@showDatailsM')->name('get.order.showDatailsM')->middleware('getRoute');

				
				


			});

			


		});
		

	});


});

app/Models/Client/Client.php
<?php

namespace App\Models\Client;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

use App\Models\Product\Order;


class Client extends Authenticatable
{
    
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','language_id','mobile','mobile2','address','more_info'
    ];
                                   

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function orders()
    {
         return $this->hasMany('App\Models\Product\Order','client_id','id')->orderBy("created_at",'DESC');
    }

}

app/Http/Controllers/Admin/Client/ClientController.php
<?php

namespace App\Http\Controllers\Admin\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Client\Client;
use App\Models\Product\Order;


class ClientController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:clients-show', ['only' => 'index', 'show']);
        $this->middleware('permission:clients-delete', ['only' =>'delete', 'deleteMulti']);
        $this->middleware('permission:clients-edit', ['only' =>'block', 'trust']);
    }

    public function index()
    {
    	$data['clients'] = Client::all();
    	return view('admin.clients.index')->with($data);
    }


    public function show($id)
    {
        $data['row'] = Client::where('id', $id)->first();
    	return view('admin.clients.show')->with($data);
    }




    // deleteing row from db  ( soft delete )
    public function delete($id)
    {
        Client::findOrFail($id)->delete();
    	session()->flash('message',trans('site.deleted_success'));
    	return back();
    }



    // Trust This Client
    public function trust(Request $request)
    {
        if($request->ajax())
        {
            $data = Client::findOrFail($request->id);
            $data->status = "trust";
            $data->save();
            $message['success'] = trans('site.blocked_success');
            return response()->json($message);
        }
    }


    // Block This Client
    public function block(Request $request)
    {

        if($request->ajax())
        {

            $data = Client::findOrFail($request->id);
            $data->status = "block";
            $data->save();
            $message['success'] = trans('site.blocked_success');
            return response()->json($message);

        }

    }





    // public function orders($id)
    // {
    //     Client::findOrFail($id);
    //     $data['orders'] = Order::select('id','name','code','email','mobile')
    //     ->where('client_id', $id)
    //     ->orderBy('id', 'DESC')
    //     ->paginate(30);
        
    //     return view('admin.clients.orders')->with($data);
    // }

    // delete mutli row from table 
    public function deleteMulti(Request $request)
    {
    	foreach ($request->deleteMulti as  $value) 
    	{
    		Client::findOrFail($value)->delete();
	    	
    	}

    	session()->flash('message',trans('site.deleted_success'));
	    return redirect(route('admin.get.message.index'));
    }


}

app/Http/Controllers/Front/Client/AuthController.php
<?php

namespace App\Http\Controllers\Front\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Client\Client;
use Jenssegers\Agent\Agent;


class AuthController extends Controller
{
    

     public function login()
     {
        $agent = new Agent();

        if($agent->isMobile())
        {
           return view('mobile.client.auth.login');

        }
        else
        {
           return view('front2.client.auth.login');
           
        }
     	 
     }


      // login authencation 
  	public function doLogin(Request $request)
    {

    	$request->validate([
    		'email'=>'required|email|max:30',
    		'password'=>'required|max:30',
    	]);
    	$remember = request()->has('remember') ? true: false;
    	if(\Auth::guard('client')->attempt(['email'=>request('email'),'password'=>request('password'),'status'=>'active']))
    	{
            if(\Cart::getTotalQuantity())
            {
                return redirect(route('front.get.order.checkout'));
            }
            else
            {

    		  return redirect(route('front.get.home.index'));
            }
    	}
    	else
    	{
    		return back()->withErrors(trans('site.errors.dataNotCorrect'));
    	}
    }// end do login function 


















    public function register()
    {

        $agent = new Agent();

        if($agent->isMobile())
        {
           return view('mobile.client.auth.register');
        }
        else
        {
           return view('front2.client.auth.login');

        }


     	
    }





    public function doRegister(Request $request)
    {
    	$request->validate([

    		'name'=>'required|string|max:100',
    		'email'=>'required|email|unique:clients,email|max:100',
    		'password'=>'required|string|max:50|min:6',
    		'confirm-password'=>'required|string|same:password|max:50',

    	]);


    	$data = new Client();
    	$data->name = $request->name;
        $data->email = $request->email;
    	$data->mobile1 = $request->mobile1;
    	$data->status = "active";
    	$data->password = bcrypt($request->password);
    	$data->save();




        if(\Auth::guard('client')->attempt(['email'=>request('email'),'password'=>request('password'),'status'=>'active']))
        {
            if(\Cart::getTotalQuantity())
            {
                return redirect(route('front.get.order.checkout'));
            }
            else
            {

              return redirect(route('front.get.home.index'));
            }
        }
        else
        {
            return back()->withErrors(trans('site.errors.dataNotCorrect'));
        }



    }


     // client logout 

    public function logout()
    {
        clientAuth()->logout();
        return redirect(route('front.get.home.index'));
    } // end logout function 




}

app/Http/Controllers/Front/Client/ForgotController.php
<?php

namespace App\Http\Controllers\Front\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Client\Client;
use App\Mail\ForgotMail;
use DB;
use Jenssegers\Agent\Agent;


class ForgotController extends Controller
{
    

     public function forgot()
     {

        $agent = new Agent();

        if($agent->isMobile())
        {
           return view('mobile.client.auth.forgot');
        }
        else
        {
           return view('front2.client.auth.forgot');

        }


     }




    public function forgotPassword(Request $request)
    {
    	 $check  = $request->validate([
    		'email'=>'required|email|exists:clients,email',

    	]);

        // $check = Client::where('email',$request->email)->first();

        if($check)
        {

            $token = str_random(32);
            DB::table('password_resets')->where('email','=',$request->email)->delete();
            DB::table('password_resets')->insert(['email' =>$request->email, 'token' => $token]);
            \Mail::to($request->email)->send(new ForgotMail($token));
            $message['success'] = trans('frontSite.checkYourEmail');
            return response()->json($message);
        }
        else
        {
            $message['success'] = trans('frontSite.emailNotFound');
            return response()->json($message);
        }

    }






    public function changePassword($token)
    {

        $check = DB::table('password_resets')->where('token','=',$token)->first();
        if($check)
        {
            $data['row'] = $check;

            $agent = new Agent();

            if($agent->isMobile())
            {
               return view('mobile.client.auth.newPassword')->with($data);
            }
            else
            {
               return view('front2.client.auth.newPassword')->with($data);
               
            }


            
        }
    }




    public function newPassword(Request $request)
    {

        if($request->ajax())
        {
            $check = DB::table('password_resets')->where('token','=',$request->base_token)->first();
            if($check)
            {
                $request->validate([
                    'password'=>'required|string|max:20|min:6',
                    'confirm-password'=>'required|string|max:20|min:6|same:password',

                ]);

                $new = Client::where('email',$check->email)->first();
                $new->password = bcrypt($request->password);
                $new->save();
                $message['success'] = true;
                return response()->json($message);
            }
            else
            {
                $message['error'] = trans('frontSite.dataNotCorrect');
                return response()->json($message);
            }
        }
        

    }







}

resources/views/mobile/client/inc/changePassword.blade.php
<div class="row">
	<div class="col-md-12 col-xs-12">
		<div class="view_die_account">
			<h3> {{ json_data($site_content,'password_title1') }} </h3>
			<hr>
			<form method="post"   id="edit-password">
				<div class="col-md-12">
                    <ul id="errors"></ul>
                </div>
				@csrf
				<p class="required">*Required field</p>

				<p class="form-row">
					<label> {{ json_data($site_content,'password_title2') }} <span class="required">*</span></label>
					<input type="password" name="oldPassword" required maxlength="100"  />
				</p>

				<p class="required">*Required field</p>
				
				<p class="form-row">
					<label>{{ json_data($site_content,'password_title3') }}<span class="required">*</span></label>
					<input type="password" name="password" required maxlength="100"  />
				</p>


				<p class="required">*Required field</p>
				
				<p class="form-row">
					<label>{{ json_data($site_content,'password_title4') }}<span class="required">*</span></label>
					<input type="password" name="confirm-password" required maxlength="100"  />
				</p>


			
				<button title="Save" class="btn btn-default button button-small" type="submit">
					<span>
						  {{ json_data($site_content,'password_title5') }}
						<i class="fa fa-chevron-right"></i>
					</span>
				</button>
			</form>
		</div>
	</div>
	
</div>

resources/views/mobile/client/inc/editInfo.blade.php
<div class="row">
	<div class="col-md-12 col-xs-12">
		<div class="view_die_account">
			<h3>{{ json_data($site_content,'Eprofile_title1') }} </h3>
			<hr>
			<form method="post" class="create-account-form" id="reg-form" action="{{route('front.client.post.auth.editProfile')}}">
				@csrf
				@include('admin.msg._messages')

				<p class="form-row">
					<label>{{ json_data($site_content,'Eprofile_title2') }} ( * )</label>
					<input type="text" name="name" value="{{clientAuth()->user()->name}}" required maxlength="100">
					
				</p>

				<p class="form-row">
					<label>{{ json_data($site_content,'Eprofile_title3') }} ( * ) </label>
					<input type="text" name="address" value="{{clientAuth()->user()->address}}" required maxlength="300">
				</p>


				<p class="form-row">
					<label>{{ json_data($site_content,'Eprofile_title4') }} ( * )  </label>
					<input type="tel" name="mobile1" value="{{clientAuth()->user()->mobile1 }}" required maxlength="100" >
				</p>

				<p class="form-row">
					<label> {{ json_data($site_content,'Eprofile_title5') }} ( optional ) </label>
					<input type="tel" name="mobile2" value="{{clientAuth()->user()->mobile2 }}"  maxlength="100" >
				</p>


				<p class="form-row">
					<label> {{ json_data($site_content,'Eprofile_title6') }} ( optional )  </label>
					<input type="tel" name="more_info" value="{{clientAuth()->user()->more_info }}"  maxlength="100" >
				</p>

				<div class="submit">					
					<button name="submitcreate" id="submitcreate" type="submit" class="">
						<span>
							<i class="fa fa-user left"></i>
							{{ json_data($site_content,'Eprofile_title7') }}
						</span>
					</button>
				</div>		
			</form>
		</div>
	</div>
	
</div>

resources/views/mobile/client/inc/info.blade.php
<div class="row">
	<div class="col-md-6 col-xs-12">
		<div class="view_die_account">
			<h3>{{ json_data($site_content,'profile_title8') }}</h3>
			<label>{{ json_data($site_content,'profile_title9') }}</label>
			<p>
				@if(clientAuth()->user()->address)
					{{clientAuth()->user()->address}}
				@else
					There Is No Default Address Untl Now
				@endif
			</p>
			<a href="{{route('front.client.get.profile.index','edit-info')}}"> {{ json_data($site_content,'profile_title10') }}  <i class="fa fa-pencil" aria-hidden="true"></i>  </a>
		</div>
	</div>
	<div class="col-md-6 col-xs-12">
		<div class="view_die_account">
			<h3>{{ json_data($site_content,'profile_title11') }}</h3>
			<label>{{clientAuth()->user()->name}}</label>
			<p>{{clientAuth()->user()->email}}</p>
			<a href="{{route('front.client.get.profile.index','change-password')}}">{{ json_data($site_content,'profile_title12') }}  <i class="fa fa-pencil" aria-hidden="true"></i>  </a>
		</div>
	</div>
</div>

resources/views/mobile/client/inc/orders.blade.php
<div class="row">
	<div class="panel-body">
	<div class="coupon-info">
		<h1 class="heading-title">  </h1>
		


		@if(clientAuth()->user()->orders)

		<table class="table table-bordered table-responsive">
			<thead>
				<tr>
					<tr>
						<th class="product-name">{{ json_data($site_content,'orders_title1') }}</th>
						<th class="product-unit-price">{{ json_data($site_content,'orders_title2') }}</th>
						<th class="product-quantity">{{ json_data($site_content,'orders_title3') }}</th>
						<th class="product-subtotal">{{ json_data($site_content,'orders_title4') }}</th>
						<th class="product-subtotal">{{ json_data($site_content,'orders_title5') }}</th>
					</tr>
				</tr>
			</thead>
			<tbody>

			@foreach(clientAuth()->user()->orders as $ord)
						
				<tr>
					<td colspan="1" class="order-info">{{ json_data($site_content,'orders_title6') }} : {{ $ord->code}}</td>
					<td colspan="2" class="order-info">{{ json_data($site_content,'orders_title7') }} : {{ date('Y-m-D',strtotime($ord->created_at))}}</td>
					<td colspan="2" class="order-info">
						<a href="{{route('front.client.get.order.showDatails',$ord->id)}}" class="btn btn-primary" style="color: #fff;">{{ json_data($site_content,'orders_title8') }}</a>
					</td>
				</tr>
				@foreach($ord->content as $co)
	


				<tr>

					<td class="product-name">
						
						<a href="#" class="img_cart">
							<img alt="{{$co->product->name}}" src="{{getImage(PRODUCT_PATH.'small/'.$co->product->img)}}">
						</a>
						<h3><a href="{{route('front.get.product.show',[$co->product->category->slug,$co->product->sub->slug,$co->product->slug])}}" class="name_cart">{{$co->product->name}}</a></h3>
						
					</td>


					<td class="product-unit-price text-center">
						<p>  EGP {{ $co->product->price}}  </p>
					</td>
					<td class="product-quantity product-cart-details text-center">
						{{$co->quantity}}
					</td>
					<td class="product-quantity  text-center">
						<p>EGP {{ $co->product->price * $co->quantity}}</p>
					</td>
					<td class="product-quantity product-cart-details text-center product-status">
						{{$co->status}}
					</td>
				</tr>



				
				@endforeach

				
				<tr><td colspan="5"></td></tr>
				<tr><td colspan="5"></td></tr>

			@endforeach

				
						
			
			</tbody>
		</table>
		@else
			
			<div class="order-history">
				<p class="alert text-center">You have not placed any orders.</p>
			</div>

		@endif




		
	</div>
</div>
</div>